name: NameLayer
main: vg.civcraft.mc.namelayer.NameLayerPlugin
version: 2.3.3
load: startup
author: Rourke750
softdepend: [Mercury]
commands:
   nlag:
   nlasg:
   nlcg:
   nldg:
   nldig:
   nlgls:
   nlgs:
   nlid:
   nlip:
   nljg:
   nllg:
   nllm:
   nllp:
   nlpp:
   nlmg:
   nlmp:
   nlrm:
   nlri:
   nlrsg:
   nlsp:
   nltg:
   nlleg:
   nllgt:
   nllpt:
   nllci:
   nltaai:
   nlcpn:
      permission: namelayer.admin
   nlsdg:
   nlgdg:
permissions:
   namelayer.admin:
      default: op
